name: 'Bundle GitHub Page'
description: 'This action bundles the current gh-page branch with the out folder'
runs:
  using: "composite"
  steps:
    - name: ➕ Create public dir
      run: mkdir public
      shell: bash
    - name: 📥 Get gh-pages tar
      run: wget https://api.github.com/repos/dbsystel/cicd-playground/repo/tarball/gh-pages -o public.tar.gz
      shell: bash
    - name: 📦 Log Tar File
      run: file public.tar.gz && cat public.tar.gz
      shell: bash
    - name: 📦 Unpack Tar
      run: tar -xf public.tar.gz -C public --strip-components 1
      shell: bash
    - name: ↔ Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: 📁 Move ./out folder to public for preview
      if: contains( github.ref, 'main') != false
      run: mv ./out ./public/${{ steps.extract_branch.outputs.branch }}.
      shell: bash
    - name: 📁 Move ./out folder to public for main
      if: contains( github.ref, 'main')
      run: mv ./out ./public
      shell: bash
