name: Deploy to gh-pages

on:
  workflow_call:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: 🔄 Init Cache
        uses: ./.github/actions/npm-cache

      - name: ⬇️Download build
        uses: actions/download-artifact@v3
        with:
          name: build
          path: out

      - name: ➕ Bundle current gh-pages
        uses: ./.github/actions/bundle-gh-page

      - name: 🥅 Deploy to GH-Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
