name: Publish Changelog

on:
  workflow_call:

jobs:
  changelog:
    name: Update Release with Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Create changelog
        run: |
          echo "CHANGELOG_TEXT=$(npx conventional-changelog-cli@2.2.2)" >> $GITHUB_ENV

      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.updateRelease({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              release_id: context.payload.release.id,
              body: process.env.CHANGELOG_TEXT
            })
