- name: Debug: Get PR Project Status
  id: get_status_debug
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run: |
    PROJECT_ITEM_ID=${{ env.ITEM_ID }}

    echo "Fetching raw project status data..."
    
    RAW_RESPONSE=$(gh api graphql -f query='
    query {
      node(id: "'"$PROJECT_ITEM_ID"'") {
        ... on ProjectV2Item {
          fieldValues(first: 10) {
            nodes {
              __typename
              field {
                ... on ProjectV2FieldCommon {
                  name
                }
              }
              ... on ProjectV2ItemFieldSingleSelectValue {
                name
              }
              ... on ProjectV2ItemFieldTextValue {
                text
              }
              ... on ProjectV2ItemFieldNumberValue {
                number
              }
            }
          }
        }
      }
    }')

    echo "Full API Response: $RAW_RESPONSE"

    echo "$RAW_RESPONSE" > project_debug.json
