name: Test and publish to registries after new tag

on:
  release:
    types: [published]

jobs:
  # init:
  #   uses: ./.github/workflows/00-init.yml

  # test:
  #   uses: ./.github/workflows/01-npm-test.yml
  #   needs: [init]

  # build:
  #   uses: ./.github/workflows/01-build.yml
  #   needs: [init]

  # cypress:
  #   uses: ./.github/workflows/01-cypress.yml
  #   needs: [build]

  publishnextnpm:
    name: Publish experimental Packages to NPM
    # needs: [test, cypress]
    # Only publish if not on the main branch, the release tag starts with a "v"
    # and is flagged as a prerelease
    if: |
      github.event.release.target_commitish != 'main' &&
      startsWith(github.ref, 'refs/tags/v') &&
      github.event.release.prerelease == true
    runs-on: ubuntu-latest
    steps:
      - name: 🔄 Init Cache
        uses: ./.github/actions/npm-cache

      - name: Publish experimental Packages to NPM
        run: |
          GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c1-7)
          SEMVER_VERSION=$(npx find-versions-cli ${{ github.event.release.tag_name }})
          echo "Semver experimental version $SEMVER_VERSION-$GITHUB_SHA_SHORT"
          npm version --no-git-tag-version $SEMVER_VERSION-$GITHUB_SHA_SHORT --workspace=@ci-cd/abcd
          npm run publish:abcd

  publishlatestnpm:
    name: Publish stable packages to NPM
    # needs: [test, cypress]
    if: github.event.release.target_commitish == 'test-package-publishing' && github.event.release.prerelease == false
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: 🔄 Init Cache
        uses: ./.github/actions/npm-cache

      - name: Publish stable packages
        run: |
          SEMVER_VERSION=$(npx find-versions-cli ${{ github.event.release.tag_name }})
          VALID_SEMVER_VERSION=$(node scripts/version-helper.js $SEMVER_VERSION)
          echo "Semver stable version unclean $SEMVER_VERSION"
          echo "Semver stable version valid $VALID_SEMVER_VERSION"
          npm version --no-git-tag-version ${{ env.VALID_SEMVER_VERSION }} --workspace=@ci-cd/abcd
          npm run publish:abcd

  publishnextgithub:
    name: Publish experimental Packages to GitHub registry
    # needs: [test, cypress]
    # Only publish if not on the main branch, the release tag starts with a "v"
    # and is flagged as a prerelease
    if: |
      github.event.release.target_commitish != 'main' &&
      startsWith(github.ref, 'refs/tags/v') &&
      github.event.release.prerelease == true
    runs-on: ubuntu-latest
    steps:
      - name: 🔄 Init Cache
        uses: ./.github/actions/npm-cache

      - name: Publish experimental Packages to GitHub
        run: |
          echo "publish next to github"

  publishlatestgithub:
    name: Publish stable packages to GitHub registry
    # needs: [test, cypress]
    if: github.event.release.target_commitish == 'test-package-publishing' && github.event.release.prerelease == false
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: 🔄 Init Cache
        uses: ./.github/actions/npm-cache

      - name: Publish stable Packages to GitHub
        run: |
          echo "publish latest to github"

  changelognext:
    uses: ./.github/workflows/changelog.yml
    needs: [publishnextgithub, publishnextnpm]

  changeloglatest:
    uses: ./.github/workflows/changelog.yml
    needs: [publishlatestgithub, publishlatestnpm]
