---
name: On-PR to main

on:
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened]
  merge_group:
    branches: ["main"]

permissions:
  pull-requests: write
  contents: write
  issues: write
  actions: read
  security-events: write

jobs:
  dependabot:
    uses: ./.github/workflows/99-auto-merge.yml

  dependabot-prettier-self-healing:
    uses: ./.github/workflows/99-auto-format-dependabot-prettier-updates.yml

  codeql:
    uses: ./.github/workflows/99-codeql-analysis.yml

  dependency-review:
    uses: ./.github/workflows/99-dependency-review.yml

  labeler:
    if: github.event.pull_request.head.repo.owner.login == 'db-ux-design-system'
    uses: ./.github/workflows/99-labeler.yml

  project-on-milestone-assignment:
    uses: ./.github/workflows/99-assign-to-project-on-milestone-set.yml
