---
name: Test upload to github release

on:
  release:
    types: [published]

jobs:
  test-upload:
    name: Build Power Apps
    runs-on: ubuntu-latest
    steps:
      - name: ⬇ Checkout repo
        uses: actions/checkout@v3

      - name: 📛 Log github
        uses: actions/github-script@v6
        with:
          script: |
            console.log('Github:' , github);
            console.log('Context:' , context);

      - name: ⬆ Upload Release Asset
        id: upload-release-asset
        uses: actions/github-script@v6
        with:
          result-encoding: json
          script: |
            const script = await import('./.github/scripts/upload-asset.js');
            const release_id = context.payload.release.id;
            const assetName = test.zip;
            const assetPath = test.zip;
            return await script({github, context, release_id, assetName, assetPath});
