name: Test and publish to registries after new tag

# on:
#   push:
#     tags: ["v[0-9].[0-9]+.[0-9]+"]
on:
  release:
    types: [published]

jobs:
  logtag:
    name: Tag Name
    # if: startsWith(github.event.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Log Tag Name
        run: |
          echo ${GITHUB_REF##*/}
          echo "event name is:" ${{ github.event_name }}
          echo "event type is:" ${{ github.event.action }}
          echo "event release is:" ${{ github.event.release }}
          echo "event release tag_name is:" ${{ github.event.release.tag_name }}
          echo "event prerelease is:" ${{ github.event.release.prerelease }}
          echo "event asset dl is:" ${{ github.event.release.assets[0].browser_download_url }}
          echo "event asset dl type is:" ${{ github.event.release.assets[0].content_type }}

  # init:
  #   uses: ./.github/workflows/00-init.yml

  # init-playground:
  #   uses: ./.github/workflows/00-init-playground.yml

  # test:
  #   uses: ./.github/workflows/01-npm-test.yml
  #   needs: [init]

  # build:
  #   uses: ./.github/workflows/01-build.yml
  #   needs: [init]

  # build-playground:
  #   uses: ./.github/workflows/01-build-playground.yml
  #   needs: [init-playground]

  # cypress:
  #   uses: ./.github/workflows/01-cypress.yml
  #   needs: [build]

  # publish:
  #   needs: [test, cypress]
  #   # if: contains( github.ref, 'test-package-publishing')
  #   uses: ./.github/workflows/02-npm-publish.yml
