name: Test and publish to registries after new tag

on:
  release:
    types: [published]

jobs:
  # init:
  #   uses: ./.github/workflows/00-init.yml

  # init-playground:
  #   uses: ./.github/workflows/00-init-playground.yml

  # test:
  #   uses: ./.github/workflows/01-npm-test.yml
  #   needs: [init]

  # build:
  #   uses: ./.github/workflows/01-build.yml
  #   needs: [init]

  # build-playground:
  #   uses: ./.github/workflows/01-build-playground.yml
  #   needs: [init-playground]

  # cypress:
  #   uses: ./.github/workflows/01-cypress.yml
  #   needs: [build]

  publishnext:
    name: Publish experimental Packages
    # needs: [test, cypress]
    # Only publish if not on the main branch, the release tag starts with a "v"
    # and is flagged as a prerelease
    if: |
      startsWith(github.ref, 'refs/tags/v') &&
      github.event.release.prerelease == true
    runs-on: ubuntu-latest
    env:
      RELEASE_CONTEXT: ${{ toJson(github.event.release) }}
      TEST_CONTEXT: ${{ toJson(github.event) }}

    steps:
      - name: Publish experimental Packages
        run: |
          echo ${GITHUB_REF##*/}
          echo "event name is:" ${{ github.event_name }}
          echo "event type is:" ${{ github.event.action }}
          echo "event release tag_name is:" ${{ github.event.release.tag_name }}
          echo "event prerelease is:" ${{ github.event.release.prerelease }}
          echo "event asset dl is:" ${{ github.event.release.assets[0].browser_download_url }}
          echo "event asset dl type is:" ${{ github.event.release.assets[0].content_type }}
          echo "RELEASE_CONTEXT: $RELEASE_CONTEXT"
          echo "TEST_CONTEXT: $TEST_CONTEXT"
          GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c1-7)
          echo "GITHUB_SHA_SHORT $GITHUB_SHA_SHORT"
          SEMVER_VERSION=$(npx find-versions-cli ${{ github.event.release.tag_name }})
          echo "Semver experimental version $SEMVER_VERSION-$GITHUB_SHA_SHORT"

  publishstable:
    name: Publish stable packages
    if: github.event.release.target_commitish == 'test-package-publishing' && github.event.release.prerelease == false
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: Publish stable packages
        run: |
          echo "We are running on: " ${{github.event.release.target_commitish}}
          SEMVER_VERSION=$(npx find-versions-cli ${{ github.event.release.tag_name }})
          VALID_SEMVER_VERSION=$(node scripts/version-helper.js $SEMVER_VERSION)
          echo "Semver stable version unclean $SEMVER_VERSION"
          echo "Semver stable version valid $VALID_SEMVER_VERSION"
