---
name: Update all PR branches if main gets update

#on:
#  push:
#    branches:
#      - "main"

jobs:
  update-prs:
    name: Update PRs
    runs-on: ubuntu-24.04 # Use Ubuntu 24.04 explicitly
    steps:
      - name: ⬇ Checkout repo
        uses: actions/checkout@v5

      - name: ⌚ Update PRs
        id: update-prs
        uses: actions/github-script@v7
        with:
          script: |
            # deactivated this for the moment, as it probably doesn't make any sense on GitHub.com with our limited runners
            # const { default: updatePrs } = await import('${{ github.workspace }}/.github/scripts/update-prs.js');
            // print how many PRs are updated
            # console.log(await updatePrs({github, context}));
