name: Sync release-candidate Branch with Main

on:
  push:
    branches:
      - main

jobs:
  sync-release-candidate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Checkout release-candidate Branch
        run: |
          git fetch origin release-candidate
          git checkout release-candidate

      - name: Merge Main into release-candidate
        run: |
          git merge main
          git push origin release-candidate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
